### PR TITLE
Convert log-add-http-post-bodies package from Bro to Zeek

### PR DESCRIPTION
**Pull request by philrz**
A user in a [Slack thread](https://zeekorg.slack.com/archives/CSZBXF6TH/p1638313695305300) expressed an interest in this package, then they paused at its current "Bro"-ness. I was in the mood to test it out (which I did successfully using the handy site [https://ptsv2.com/)](https://ptsv2.com/)) so here's a quick PR to make it `zkg`\-installable.

### CODE REVIEW

**Review by awelzel — APPROVED** [review]

**Comment by awelzel** [comment]
@ckreibich / @sethhall - do you have permissions to merge this PR or is there a replacement package that does the same these days?

**Comment by keithjjones** [comment]
+1

```
% zkg install log-add-http-post-bodies
Package zeek/corelight/log-add-http-post-bodies is using the legacy bro-pkg.meta metadata file. It will soon stop working unless updated to use zkg.meta instead. Please report this to the package maintainers.
The following packages will be INSTALLED:
  zeek/corelight/log-add-http-post-bodies (master)

Proceed? [Y/n]
```

**Comment by keithjjones** [comment]
Also:

```
% zeek -Cr ../solarmarker.pcap packages
error in /Users/keith.jones/zeek/share/zeek/site/packages/__load__.zeek, line 4: Failed to open package '/Users/keith.jones/zeek/share/zeek/site/packages/./log-add-http-post-bodies': missing '__load__.zeek' file
fatal error in /Users/keith.jones/zeek/share/zeek/site/packages/__load__.zeek, line 4: can't open /Users/keith.jones/zeek/share/zeek/site/packages/./log-add-http-post-bodies/__load__.zeek
```

Since they have "bro" extension they are not being loaded.

**Comment by ckreibich** [comment]
Apologies for the delay here. I've merged this. I did not tag it as a release, since the package has no prior ones. I did some manual testing to verify that the package still works. A test case contribution for this one would be very welcome.

**Pull request merged**
